### ISSUE TITLE
Bug with Autolayout trailing constraint

### ISSUE THREAD

**Issue by smaroff92** [mumty13/MHSoftUI#1]
Hello, when using autolayot it's trailing constraint not corrected. How to fix it?

**Comment by mumty13** [comment]
I don't get it, can you share a screenshot?
If you see the example, the stop button (on the right side) is having a trailing constraint.

**Comment by smaroff92** [comment]
In the example the stop button has a width. I'm not using width.
<img width="304" alt="Снимок экрана 2020-01-27 в 17 07 56" src="https://user-images.githubusercontent.com/44186336/73170119-d0277c00-4127-11ea-801b-c62d81813b2e.png">

**Comment by mumty13** [comment]
It works perfectly even without using fixed width. Make sure you're giving a trailing constraint to your view/button **BEFORE** calling the soft ui effect method.

**Comment by smaroff92** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-27 at 17 24 57](https://user-images.githubusercontent.com/44186336/73171058-0cf47280-412a-11ea-9f36-06f8d6420491.png)

This is on your example, here heart button have leading and trailing constraints (without width) alse here  viewForSoftUI have leading and trailing constraint instead of width

**Comment by mumty13** [comment]
Thanks for highlighting, there is indeed a problem when used with trailing constraint, I'll look into it and send a new version.

**Comment by smaroff92** [comment]
Thank You!

**Comment by mumty13** [comment]
@smaroff92 you must be calling the methods inside `viewDidLoad()`, at which time controller hasn't yet calculated views sizes.
Instead, call these methods inside `viewDidAppear(_ animated: Bool)` and everything should work fine with auto layouts.
I've edited the "readme" file and updated this important requirement, and adjusted the example too:
```
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    backgroundView.addSoftUIEffectForView()
    labelBackView.addSoftUIEffectForView()
        
    stopButton.addSoftUIEffectForButton()
    likeButton.addSoftUIEffectForButton(cornerRadius: 0)
    playButton.addSoftUIEffectForButton(cornerRadius: playButton.bounds.height/2)
}
```
