### ISSUE TITLE
button Aren't working as required

### ISSUE THREAD

**Issue by Sid7862** [mumty13/MHSoftUI#3]
Hi ,
I went through the above project and was really impressed by your work but unfortunately the button aren't working as the above screenshot suggest. And one more suggestion can you added a pressed state in UIView

**Comment by mumty13** [comment]
Can you share a bit more details on how buttons aren't working, and a screenshot that might highlight the problem. Thanks!

**Comment by mumty13** [comment]
Button animation is now fixed, check
https://github.com/mumty13/MHSoftUI/issues/4#issuecomment-778677140
