### ISSUE TITLE
Button doesn't work

### ISSUE THREAD

**Issue by danilolutti** [mumty13/MHSoftUI#4]
Style is applied but when I click on a button in your example, appearance doesn't change to "pressed".
XCode 12.

**Comment by mumty13** [comment]
@danilolutti you're right, animation is not working anymore. It seems I'm gonna have to make a subclass for the buttons. Will update the library soon. Thank you for creating this issue.

**Comment by mumty13** [comment]
Issue has been resolved, animations to buttons are restored.
We now need to have our buttons created with the class MHSoftUIButton() like following example:
`let myButton = MHSoftUIButton()`
and then add softUIEffect by calling its method. Also make sure MHSoftUIButton reference is given to buttons in Storyboard or Xib as well if you're using any of those.

Thanks again,
Issue is going to get closed now.
